import scrollToSectionSide from "./modules/scrollToSectionSide.js";
import scrollToSectionNavBar from "./modules/scrollToSectionNavBar.js";
import typeWriter from "./modules/typeWriter.js";
import form from "./modules/form.js";
import sectionReveal from "./modules/sectionReveal.js";
import sectionThreeObserver from "./modules/sectionThreeObserver.js";
import sectionTwoObserver from "./modules/sectionTwoObserver.js";
import popup from "./modules/popup.js";
import sideBtnColor from "./modules/sideBtnColor.js";
